name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Tests
      run: |
        echo -- Running Test cases --
        docker-compose -f "docker-compose.yml" up -d --build
    - name: stop containers
      if: ${{ always() }}
      run: docker-compose -f "docker-compose.yml" down
        
